hw02 is completed
soadmized/go_otus pull request #2
Opened 2023-06-25 20:56 UTC by soadmized

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-26 05:48 UTC, ityulkanov requested changes
добавьте, пожалуйста тесты, лучше всего если с utf в строке, и необходимо поправить немного путь к модулю.

2023-06-26 05:48 UTC, ityulkanov commented on hw02_unpack_string/go.mod
> +module github.com/soadmized/hw02_unpack_string
здесь необходимо прописать полный путь к модулю

2023-06-26 05:48 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +	_, err := strconv.Atoi(string(s[0]))
тут будет работать с ascii но вот насчёт utf символов не уверен, вероятно будет err. Попробуйте добавить какой нибудь символ вроде флага в строку и прописать в тесте. Ну и вообще можно добавить теста 3-4 с какими нибудь экзотическими utf символвами

2023-06-26 06:10 UTC, soadmized commented on hw02_unpack_string/go.mod
> +module github.com/soadmized/hw02_unpack_string
Поправлю

2023-06-26 06:10 UTC, soadmized commented on hw02_unpack_string/unpack.go
> +	_, err := strconv.Atoi(string(s[0]))
Поправлю

2023-06-27 10:39 UTC, ityulkanov requested changes
Поправьте, пожалуйста ошибку с обработкой err

2023-06-27 10:39 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +	if err == nil {
```suggestion
	if err != nil {
```

2023-06-28 20:29 UTC, soadmized commented on hw02_unpack_string/unpack.go
> +	if err == nil {
Тут я подразумевал такую логику - если первый элемент строки конвертится без ошибки - значит это цифра, т.е строка невалидная

2023-07-03 10:44 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +	if err == nil {
Всё понял, замечание удаляю.

2023-07-03 10:44 UTC, ityulkanov approved these changes

2023-07-14 07:42 UTC, merged